export const timeZones = [
  { value: "UTC", label: "Coordinated Universal Time (UTC)" },
  { value: "GMT", label: "Greenwich Mean Time (GMT)" },
  { value: "BST", label: "British Summer Time (BST)" },
  { value: "CET", label: "Central European Time (CET)" },
  { value: "CEST", label: "Central European Summer Time (CEST)" },
  { value: "EET", label: "Eastern European Time (EET)" },
  { value: "EEST", label: "Eastern European Summer Time (EEST)" },
  { value: "WET", label: "Western European Time (WET)" },
  { value: "WEST", label: "Western European Summer Time (WEST)" },
  { value: "AST", label: "Atlantic Standard Time (AST)" },
  { value: "ADT", label: "Atlantic Daylight Time (ADT)" },
  { value: "EST", label: "Eastern Standard Time (EST)" },
  { value: "EDT", label: "Eastern Daylight Time (EDT)" },
  { value: "CST", label: "Central Standard Time (CST)" },
  { value: "CDT", label: "Central Daylight Time (CDT)" },
  { value: "MST", label: "Mountain Standard Time (MST)" },
  { value: "MDT", label: "Mountain Daylight Time (MDT)" },
  { value: "PST", label: "Pacific Standard Time (PST)" },
  { value: "PDT", label: "Pacific Daylight Time (PDT)" },
  { value: "AKST", label: "Alaska Standard Time (AKST)" },
  { value: "AKDT", label: "Alaska Daylight Time (AKDT)" },
  { value: "HAST", label: "Hawaii-Aleutian Standard Time (HAST)" },
  { value: "HADT", label: "Hawaii-Aleutian Daylight Time (HADT)" },
];
