import {
  MemberstackProtected,
  useMember,
  useMemberstack,
} from "@memberstack/react";
import "./globals.css";
import { Inter } from "next/font/google";
import { MemberInformationContext } from "@/lib/components/context";
import Fallback from "../fallback/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  slot_authenticated: React.ReactNode;
  slot_unauthenticated: React.ReactNode;
}) {
  // this includes all the member/user information from Memberstack (https://app.memberstack.io/dashboard)
  const user = useMember();
  const memberstack = useMemberstack();
  // conditionally render the authenticated or unauthenticated slot or a simple children slot
  return (
    <MemberstackProtected
      allow={{
        plans: ["planid102020", "planid102021"],
        permissions: ["permissionid102020", "permissionid102021"],
      }}
      onUnauthorized={<Fallback />}
    >
      <MemberInformationContext.Provider value={{ user, memberstack }}>
        {children}
      </MemberInformationContext.Provider>
    </MemberstackProtected>
  );
}
