export const TABLETITLESECTION = {
  desc: "desc",
  asc: "asc",
  company: "company",
  event: "event",
  status: "status",
  pricingDate: "pricingDate",
  priceRange: "priceRange",
  proceedsRange: "proceedsRange",
  symbol: "symbol",
  last30D: "last30D",
  price: "price",
  daily: "daily",
  vol: "vol",
  today: "today",
  marketCap: "marketCap",
};

export const FOOTER = {
  stayInTheKnow: "stay in the know",
  getFreeWeeklyUpdates: "Get free weekly updates",
  iAgreeToThe: "I agree to the ",
  termAndConditions: "Terms & Conditions ",
  ofSubscription: "of subscription",
  unlockPremiumFeatures: "unlock PREMIUM features",
  detailPremiumFeature:
    "Take advantage of all the power tools we have to offer including:",
  pointOne: "Access to all of the Pro Data",
  pointTwo: "Morning Newsletters and Activity Alerts",
  pointThree: "Export data to Excel/CSV with Pro subscription",
  pricing: "Pricing starts at $X.",
  subscribe: "SUBSCRIBE",
  unlockProAccess: "UNLOCK PRO ACCESS",
  portals: "Portals",
  support: "support",
  connectWithUs: "Connect with us",
  listingTrack: "ListingTrack",
  IPOs: "IPOs",
  mergers: "Mergers",
  SPACs: "SPACs",
  upgradePlan: "Upgrade plan",
  FAQs: "FAQs",
  policies: "Policies",
  contactUs: "Contact us",
  twitter: "Twitter",
  commonFi: "Common.fi",
  copyRights: "IPO and Public M&A Intel for All",
};

export const sidebarItem = [
  {
    name: "Home",
    pathname: "/home",
    id: "home",
    breadcrumb: "Home",
  },
  {
    name: "IPOs",
    pathname: "/ipos/hub",
    id: "ipos/hub",
    breadcrumb: "Home > IPOs > HUB",
    items: [
      {
        name: "HUB",
        pathname: "/ipos/hub",
        id: "ipos/hub",
        breadcrumb: "Home > IPOs > HUB",
      },
      {
        name: "STATS",
        pathname: "/ipos/stats",
        id: "ipos/stats",
        breadcrumb: "Home > IPOs > STATS",
      },
      {
        name: "PIPELINE",
        pathname: "/ipos/pipeline",
        id: "ipos/pipeline",
        breadcrumb: "Home > IPOs > PIPELINE",
      },
      {
        name: "NEWS",
        pathname: "/ipos/news",
        id: "ipos/news",
        breadcrumb: "Home > IPOs > NEWS",
      },
      {
        name: "SCREENERS",
        pathname: "/ipos/screeners",
        id: "ipos/screeners",
        breadcrumb: "Home > IPOs > SCREENERS",
      },
      {
        name: "LIST",
        pathname: "/ipos/list",
        id: "ipos/list",
        breadcrumb: "Home > IPOs > List",
      },
    ],
  },
  {
    name: "Mergers",
    pathname: "/mergers/hub",
    id: "mergers/hub",
    breadcrumb: "Home > MERGERS > HUB",

    items: [
      {
        name: "HUB",
        pathname: "/mergers/hub",
        id: "mergers/hub",
        breadcrumb: "Home > MERGERS > HUB",
      },
      {
        name: "STATS",
        pathname: "/mergers/stats",
        id: "mergers/stats",
        breadcrumb: "Home > MERGERS > STATS",
      },
      {
        name: "PIPELINE",
        pathname: "/mergers/pipeline",
        id: "mergers/pipeline",
        breadcrumb: "Home > MERGERS > PIPELINE",
      },
      {
        name: "NEWS",
        pathname: "/mergers/news",
        id: "mergers/news",
        breadcrumb: "Home > MERGERS > NEWS",
      },
      {
        name: "SCREENERS",
        pathname: "/mergers/screeners",
        id: "mergers/screeners",
        breadcrumb: "Home > MERGERS > SCREENERS",
      },
      {
        name: "LIST",
        pathname: "/mergers/list",
        id: "mergers/list",
        breadcrumb: "Home > MERGERS > List",
      },
    ],
  },
  {
    name: "SPACs",
    pathname: "/spacs/hub",
    id: "/spacs/hub",
    breadcrumb: "Home > SPACs > HUB",
    items: [
      {
        name: "HUB",
        pathname: "/spacs/hub",
        id: "spacs/hub",
        breadcrumb: "Home > SPACs > HUB",
      },
      {
        name: "STATS",
        pathname: "/spacs/stats",
        id: "spacs/stats",
        breadcrumb: "Home > SPACs > STATS",
      },
      {
        name: "PIPELINE",
        pathname: "/spacs/pipeline",
        id: "spacs/pipeline",
        breadcrumb: "Home > SPACs > PIPELINE",
      },
      {
        name: "NEWS",
        pathname: "/spacs/news",
        id: "spacs/news",
        breadcrumb: "Home > SPACs > NEWS",
      },
      {
        name: "SCREENERS",
        pathname: "/spacs/screeners",
        id: "spacs/screeners",
        breadcrumb: "Home > SPACs > SCREENERS",
      },
      {
        name: "LIST",
        pathname: "/spacs/list",
        id: "spacs/list",
        breadcrumb: "Home > SPACs > List",
      },
    ],
  },
  {
    name: "Watchlist",
    pathname: "/watchlist",
    id: "watchlist",
    breadcrumb: "watchlist",
  },
];

export const navBarText = {
  signUp: "Sign up",
  signIn: "Sign in",
};

export const homeConstants = {
  title: "LISTINGTRACK",
  IOPS: "IPOS",
  SPACS: "SPACS",
  MERGERS: "MERGERS",
  details:
    "Lorem ipsum dolor sit amet consectetur. Turpis pretium ut elementum quisque parturie. Turpis pretium ut elementum quisque parturie.",
  COMPARISON: "COMPARISON",
  chartTitle: "2022 YTD Event Summary",
  IPOPipeline: {
    title: "IPO Pipeline",
    Company: "Company",
    Event: "Event",
    Status: "Status",
    EstPricingDate: "Est. Pricing Date",
    PriceRange: "Price/range",
    ProceedsRange: "Proceeds/range",
  },
  MergersPipeline: {
    title: "Merger Pipeline",
  },
  AggrecatedMiniTable: {
    title: "Aggregated Mini-tables",
    ListingTrack: "ListingTrack",
    MERGERs: "MERGERs (>$2B)",
    Livemergers: "Live mergers",
    withspacs: "with spacs",
    SANSspacs: "SANS spacs",
    completed: "completed",
    mergers: "mergers",
    Totalactive: "Total active",
    Searching: "Searching",
    Live: "Live",
    IPOs: "IPOs",
    IPOSWITHSPACS: "IPOS WITH SPACS",
    MERGERSWITHSPACS: "MERGERS WITH SPACS",
    MERGERSSANSSPACS: "MERGERS SANS SPACS",
    IPOSSANSSPACS: "IPOS SANS SPACS",
    YTD: "YTD",
    AVGRETURN: "AVG. RETURN",
    SPACs: "SPACs",
    ShowSPACs: "Show SPACs",
  },
};

export const weekName = [
  "JAN",
  "FEB",
  "MAR",
  "APR",
  "MAY",
  "JUN",
  "JUL",
  "AUG",
  "SEP",
  "OCT",
  "NOV",
  "DEC",
];

export const PreDealSpacScreener = [
  {
    name: "Company",
    key: "company",
    type: "string",
    pro: false,
  },
  {
    name: "Symbol",
    key: "symbol",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Method",
    key: "listing_method",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Status",
    key: "listing_status",
    type: "string",
    pro: false,
  },
  {
    name: "Exchange",
    key: "daily",
    type: "string",
    pro: false,
  },
  {
    name: "Market Cap",
    key: "marketCap",
    type: "string",
    pro: false,
  },
  {
    name: "Region",
    key: "Region",
    type: "string",
    pro: true,
  },
  {
    name: "Sector",
    key: "Sector",
    type: "string",
    pro: true,
  },
  {
    name: "Industry",
    key: "Industry",
    type: "string",
    pro: true,
  },
  {
    name: "HQ City, Country",
    key: "HQCityCountry",
    type: "string",
    pro: true,
  },
  {
    name: "Employees",
    key: "Employees",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Status",
    key: "IPOStatus",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Type",
    key: "IPOType",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Price",
    key: "IPOPrice",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Date",
    key: "IPODate",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Proceeds",
    key: "IPOProceeds",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Underwriters",
    key: "IPOUnderwriters",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Date",
    key: "ExpectedIPODate",
    type: "string",
    pro: false,
  },
  {
    name: "ExpectedIPOShares",
    key: "ExpectedIPOShares",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Price Range",
    key: "ExpectedIPOPriceRange",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Valuation",
    key: "ExpectedIPOValuation",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Market Cap",
    key: "IPOMarketCap",
    type: "string",
    pro: true,
  },
  {
    name: "IPO S-1 Registration Link",
    key: "IPOS1RegistrationLink",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Filed Date",
    key: "IPOFiledDate",
    type: "string",
    pro: true,
  },
  {
    name: "Registration Domicile",
    key: "RegistrationDomicile",
    type: "string",
    pro: true,
  },
  {
    name: "S-1 Withdrawal Date",
    key: "S1WithdrawalDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Date",
    key: "IPORumorDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Publication",
    key: "IPORumorPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Source",
    key: "IPORumorSource",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Date",
    key: "IPOStallDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Publication",
    key: "IPOStallPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Source",
    key: "IPOStallSource",
    type: "string",
    pro: true,
  },
  {
    name: "Latest Price",
    key: "LatestPrice",
    type: "string",
    pro: false,
  },
  {
    name: "1-day Price Chg %",
    key: "1dayPriceChg",
    type: "string",
    pro: false,
  },
  {
    name: "Outstanding Shares",
    key: "OutstandingShares",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week High",
    key: "52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week Low",
    key: "52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week High Percent Change",
    key: "52WeekHighPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week Low Percent Change",
    key: "52WeekLowPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Volume",
    key: "Volume",
    type: "string",
    pro: false,
  },
  {
    name: "Average 30 Day Volume",
    key: "Average30DayVolume",
    type: "string",
    pro: false,
  },
  {
    name: "YTD Percent Change",
    key: "YTDPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Optionable",
    key: "Optionable",
    type: "string",
    pro: false,
  },
  {
    name: "1-week Percent Change ",
    key: "1weekPercentChange ",
    type: "string",
    pro: true,
  },
  {
    name: "30-day Change Percent",
    key: "30dayChangePercent",
    type: "string",
    pro: true,
  },
  {
    name: "1-month Percent Change",
    key: "1monthPercentChange",
    type: "string",
    pro: true,
  },
  {
    name: "3-month Percent Change",
    key: "3monthPercentChange",
    type: "string",
    pro: true,
  },
  {
    name: "1-year Percent Change ",
    key: "1yearPercentChange ",
    type: "string",
    pro: true,
  },
  {
    name: "Warrant Symbol",
    key: "WarrantSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Latest Warrant Price",
    key: "LatestWarrantPrice",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Price Change Previous",
    key: "WarrantPriceChangePrevious",
    type: "string",
    pro: false,
  },
  {
    name: "SPAC Warrant Intrinsic Value",
    key: "SPACWarrantIntrinsicValue",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant 52-Week High",
    key: "Warrant52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant 52-Week Low",
    key: "Warrant52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Percent Change 52-Week High",
    key: "WarrantPercentChange52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Percent Change 52-Week Low",
    key: "WarrantPercentChange52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Volume",
    key: "WarrantVolume",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Average 30 Day Volume",
    key: "WarrantAverage30DayVolume",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Return YTD",
    key: "WarrantReturnYTD",
    type: "string",
    pro: false,
  },
  {
    name: "Unit Symbol",
    key: "UnitSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Latest Unit Price",
    key: "LatestUnitPrice",
    type: "string",
    pro: false,
  },
  {
    name: "Unit Price Change Previous Day",
    key: "UnitPriceChangePreviousDay",
    type: "string",
    pro: false,
  },
  {
    name: "Unit Outstanding Shares",
    key: "UnitOutstandingShares",
    type: "string",
    pro: false,
  },
  {
    name: "Unit 52-Week High",
    key: "Unit52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "Unit 52-Week Low",
    key: "Unit52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "Unit 52-Week High Percent Change",
    key: "Unit52WeekHighPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Unit 52-Week Low Percent Change",
    key: "Unit52WeekLowPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Unit Volume",
    key: "UnitVolume",
    type: "string",
    pro: false,
  },
  {
    name: "Unit YTD Percent Change",
    key: "UnitYTDPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Percent Change 1-week",
    key: "WarrantPercentChange1week",
    type: "string",
    pro: true,
  },
  {
    name: "Warrant Percent Change 1-month",
    key: "WarrantPercentChange1month",
    type: "string",
    pro: true,
  },
  {
    name: "Warrant Percent Change 1-year",
    key: "WarrantPercentChange1year",
    type: "string",
    pro: true,
  },
  {
    name: "Unit 1-month Percent Change",
    key: "Unit1monthPercentChange",
    type: "string",
    pro: true,
  },
  {
    name: "SPAC Progress Status",
    key: "SPACProgressStatus",
    type: "string",
    pro: false,
  },
  {
    name: "Desired Target Focus",
    key: "DesiredTargetFocus",
    type: "string",
    pro: false,
  },
  {
    name: "Prominent Leaders",
    key: "ProminentLeaders",
    type: "string",
    pro: false,
  },
  {
    name: "Unit and Warrant Conversion Details",
    key: "UnitandWarrantConversionDetails",
    type: "string",
    pro: false,
  },
  {
    name: "Split Date",
    key: "SplitDate",
    type: "string",
    pro: false,
  },
  {
    name: "Initial SPAC Deadline Date",
    key: "InitialSPACDeadlineDate",
    type: "string",
    pro: false,
  },
  {
    name: "Est. SPAC Deadline Date",
    key: "EstSPACDeadlineDate",
    type: "string",
    pro: false,
  },
  {
    name: "Time Progress to SPAC Deadline",
    key: "TimeProgresstoSPACDeadline",
    type: "string",
    pro: false,
  },
  {
    name: "Extension Details",
    key: "ExtensionDetails",
    type: "string",
    pro: false,
  },
  {
    name: "Latest SPAC Extension Shareholder Vote Date",
    key: "LatestSPACExtensionShareholderVoteDate",
    type: "string",
    pro: false,
  },
  {
    name: "DespacCloseDate",
    key: "DespacCloseDate",
    type: "string",
    pro: false,
  },
  {
    name: "Post-SPAC Merger Estimated Warrant Exercisable Date",
    key: "PostSPACMergerEstimatedWarrantExercisableDate",
    type: "string",
    pro: false,
  },
  {
    name: "Post-SPAC Merger Warrant Exercise Deadline Date",
    key: "PostSPACMergerWarrantExerciseDeadlineDate",
    type: "string",
    pro: false,
  },
  {
    name: "Latest SPAC Extension Proxy Link",
    key: "LatestSPACExtensionProxyLink",
    type: "string",
    pro: true,
  },
  {
    name: "SPAC Latest Extension Vote Redemption Deadline Date",
    key: "SPACLatestExtensionVoteRedemptionDeadlineDate",
    type: "string",
    pro: true,
  },
  {
    name: "SPAC Latest Extension Vote Ex-Redemption Date",
    key: "SPACLatestExtensionVoteExRedemptionDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Vote Redemption Deadline Date",
    key: "MergerVoteRedemptionDeadlineDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Vote Ex-Redemption Date",
    key: "MergerVoteExRedemptionDate",
    type: "string",
    pro: true,
  },
  {
    name: "Latest Post-SPAC Merger Share Registration S-1 Link",
    key: "LatestPostSPACMergerShareRegistrationS1Link",
    type: "string",
    pro: true,
  },
  {
    name: "Post-SPAC Merger Share Registration Effective Date",
    key: "PostSPACMergerShareRegistrationEffectiveDate",
    type: "string",
    pro: true,
  },
  {
    name: "Liquidation Date",
    key: "LiquidationDate",
    type: "string",
    pro: true,
  },
  {
    name: "Liquidation Redemption Price",
    key: "LiquidationRedemptionPrice",
    type: "string",
    pro: true,
  },
  {
    name: "Liquidation Announcement Link",
    key: "LiquidationAnnouncementLink",
    type: "string",
    pro: true,
  },
  {
    name: "Liquidation Trust Value",
    key: "LiquidationTrustValue",
    type: "string",
    pro: true,
  },
  {
    name: "Est. Trust Value",
    key: "EstTrustValue",
    type: "string",
    pro: false,
  },
  {
    name: "Trust per Share",
    key: "TrustperShare",
    type: "string",
    pro: false,
  },
  {
    name: "Trust Per Share Date",
    key: "TrustPerShareDate",
    type: "string",
    pro: false,
  },
  {
    name: "Est. Shares Remaining Pre-Close (M)",
    key: "EstSharesRemainingPreCloseM",
    type: "string",
    pro: false,
  },
  {
    name: "Est. Shares Remaining Post-Close (M)",
    key: "EstSharesRemainingPostCloseM",
    type: "string",
    pro: false,
  },
  {
    name: "Trust P.S. at IPO",
    key: "TrustPSatIPO",
    type: "string",
    pro: true,
  },
  {
    name: "Trust per Share Source",
    key: "TrustperShareSource",
    type: "string",
    pro: true,
  },
  {
    name: "Trading Premium/Discount",
    key: "TradingPremiumDiscount",
    type: "string",
    pro: true,
  },
  {
    name: "SPAC Shares Redeemed at Merger Vote (%)",
    key: "SPACSharesRedeemedatMergerVote",
    type: "string",
    pro: true,
  },
  {
    name: "SPAC Shares Redeemed Lifetime (%)",
    key: "SPACSharesRedeemedLifetime",
    type: "string",
    pro: true,
  },
];

export const CompanyProfile = [
  {
    name: "Company",
    key: "companyName",
    type: "string",
    pro: false,
  },
  {
    name: "Symbol",
    key: "companySymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Method",
    key: "listing_method",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Status",
    key: "listing_status",
    type: "string",
    pro: false,
  },
  {
    name: "Exchange",
    key: "daily",
    type: "string",
    pro: false,
  },
  {
    name: "Market Cap",
    key: "marketCap",
    type: "string",
    pro: false,
  },
  {
    name: "Region",
    key: "Region",
    type: "string",
    pro: true,
  },
  {
    name: "Sector",
    key: "Sector",
    type: "string",
    pro: true,
  },
  {
    name: "Industry",
    key: "Industry",
    type: "string",
    pro: true,
  },
  {
    name: "HQ City, Country",
    key: "HQCityCountry",
    type: "string",
    pro: true,
  },
  {
    name: "Employees",
    key: "Employees",
    type: "string",
    pro: true,
  },
];
export const IPOProfile = [
  {
    name: "IPO Status",
    key: "IPOStatus",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Type",
    key: "IPOType",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Price",
    key: "IPOPrice",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Date",
    key: "IPODate",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Proceeds",
    key: "IPOProceeds",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Underwriters",
    key: "IPOUnderwriters",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Date",
    key: "ExpectedIPODate",
    type: "string",
    pro: false,
  },
  {
    name: "ExpectedIPOShares",
    key: "ExpectedIPOShares",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Price Range",
    key: "ExpectedIPOPriceRange",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Valuation",
    key: "ExpectedIPOValuation",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Market Cap",
    key: "IPOMarketCap",
    type: "string",
    pro: true,
  },
  {
    name: "IPO S-1 Registration Link",
    key: "IPOS1RegistrationLink",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Filed Date",
    key: "IPOFiledDate",
    type: "string",
    pro: true,
  },
  {
    name: "Registration Domicile",
    key: "RegistrationDomicile",
    type: "string",
    pro: true,
  },
  {
    name: "S-1 Withdrawal Date",
    key: "S1WithdrawalDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Date",
    key: "IPORumorDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Publication",
    key: "IPORumorPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Source",
    key: "IPORumorSource",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Date",
    key: "IPOStallDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Publication",
    key: "IPOStallPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Source",
    key: "IPOStallSource",
    type: "string",
    pro: true,
  },
];

export const Trading = [
  {
    name: "Latest Price",
    key: "LatestPrice",
    type: "string",
    pro: false,
  },
  {
    name: "1-day Price Chg %",
    key: "1dayPriceChg",
    type: "string",
    pro: false,
  },
  {
    name: "Outstanding Shares",
    key: "OutstandingShares",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week High",
    key: "52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week Low",
    key: "52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week High Percent Change",
    key: "52WeekHighPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week Low Percent Change",
    key: "52WeekLowPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Volume",
    key: "Volume",
    type: "string",
    pro: false,
  },
  {
    name: "Average 30 Day Volume",
    key: "Average30DayVolume",
    type: "string",
    pro: false,
  },
  {
    name: "YTD Percent Change",
    key: "YTDPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Optionable",
    key: "Optionable",
    type: "string",
    pro: false,
  },
  {
    name: "1-week Percent Change ",
    key: "1weekPercentChange ",
    type: "string",
    pro: true,
  },
  {
    name: "30-day Change Percent",
    key: "30dayChangePercent",
    type: "string",
    pro: true,
  },
  {
    name: "1-month Percent Change",
    key: "1monthPercentChange",
    type: "string",
    pro: true,
  },
  {
    name: "3-month Percent Change",
    key: "3monthPercentChange",
    type: "string",
    pro: true,
  },
  {
    name: "1-year Percent Change ",
    key: "1yearPercentChange ",
    type: "string",
    pro: true,
  },
];
export const SPACTrading = [
  {
    name: "Warrant Symbol",
    key: "WarrantSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Latest Warrant Price",
    key: "LatestWarrantPrice",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Price Change Previous",
    key: "WarrantPriceChangePrevious",
    type: "string",
    pro: false,
  },
  {
    name: "SPAC Warrant Intrinsic Value",
    key: "SPACWarrantIntrinsicValue",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant 52-Week High",
    key: "Warrant52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant 52-Week Low",
    key: "Warrant52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Percent Change 52-Week High",
    key: "WarrantPercentChange52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Percent Change 52-Week Low",
    key: "WarrantPercentChange52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Volume",
    key: "WarrantVolume",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Average 30 Day Volume",
    key: "WarrantAverage30DayVolume",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Return YTD",
    key: "WarrantReturnYTD",
    type: "string",
    pro: false,
  },
  {
    name: "Unit Symbol",
    key: "UnitSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Latest Unit Price",
    key: "LatestUnitPrice",
    type: "string",
    pro: false,
  },
  {
    name: "Unit Price Change Previous Day",
    key: "UnitPriceChangePreviousDay",
    type: "string",
    pro: false,
  },
  {
    name: "Unit Outstanding Shares",
    key: "UnitOutstandingShares",
    type: "string",
    pro: false,
  },
  {
    name: "Unit 52-Week High",
    key: "Unit52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "Unit 52-Week Low",
    key: "Unit52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "Unit 52-Week High Percent Change",
    key: "Unit52WeekHighPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Unit 52-Week Low Percent Change",
    key: "Unit52WeekLowPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Unit Volume",
    key: "UnitVolume",
    type: "string",
    pro: false,
  },
  {
    name: "Unit YTD Percent Change",
    key: "UnitYTDPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Warrant Percent Change 1-week",
    key: "WarrantPercentChange1week",
    type: "string",
    pro: true,
  },
  {
    name: "Warrant Percent Change 1-month",
    key: "WarrantPercentChange1month",
    type: "string",
    pro: true,
  },
  {
    name: "Warrant Percent Change 1-year",
    key: "WarrantPercentChange1year",
    type: "string",
    pro: true,
  },
  {
    name: "Unit 1-month Percent Change",
    key: "Unit1monthPercentChange",
    type: "string",
    pro: true,
  },
];

export const SPACProfile = [
  {
    name: "SPAC Progress Status",
    key: "SPACProgressStatus",
    type: "string",
    pro: false,
  },
  {
    name: "Desired Target Focus",
    key: "DesiredTargetFocus",
    type: "string",
    pro: false,
  },
  {
    name: "Prominent Leaders",
    key: "ProminentLeaders",
    type: "string",
    pro: false,
  },
  {
    name: "Unit and Warrant Conversion Details",
    key: "UnitandWarrantConversionDetails",
    type: "string",
    pro: false,
  },
  {
    name: "Split Date",
    key: "SplitDate",
    type: "string",
    pro: false,
  },
  {
    name: "Initial SPAC Deadline Date",
    key: "InitialSPACDeadlineDate",
    type: "string",
    pro: false,
  },
  {
    name: "Est. SPAC Deadline Date",
    key: "EstSPACDeadlineDate",
    type: "string",
    pro: false,
  },
  {
    name: "Time Progress to SPAC Deadline",
    key: "TimeProgresstoSPACDeadline",
    type: "string",
    pro: false,
  },
  {
    name: "Extension Details",
    key: "ExtensionDetails",
    type: "string",
    pro: false,
  },
  {
    name: "Latest SPAC Extension Shareholder Vote Date",
    key: "LatestSPACExtensionShareholderVoteDate",
    type: "string",
    pro: false,
  },
  {
    name: "DespacCloseDate",
    key: "DespacCloseDate",
    type: "string",
    pro: false,
  },
  {
    name: "Post-SPAC Merger Estimated Warrant Exercisable Date",
    key: "PostSPACMergerEstimatedWarrantExercisableDate",
    type: "string",
    pro: false,
  },
  {
    name: "Post-SPAC Merger Warrant Exercise Deadline Date",
    key: "PostSPACMergerWarrantExerciseDeadlineDate",
    type: "string",
    pro: false,
  },
  {
    name: "Latest SPAC Extension Proxy Link",
    key: "LatestSPACExtensionProxyLink",
    type: "string",
    pro: true,
  },
  {
    name: "SPAC Latest Extension Vote Redemption Deadline Date",
    key: "SPACLatestExtensionVoteRedemptionDeadlineDate",
    type: "string",
    pro: true,
  },
  {
    name: "SPAC Latest Extension Vote Ex-Redemption Date",
    key: "SPACLatestExtensionVoteExRedemptionDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Vote Redemption Deadline Date",
    key: "MergerVoteRedemptionDeadlineDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Vote Ex-Redemption Date",
    key: "MergerVoteExRedemptionDate",
    type: "string",
    pro: true,
  },
  {
    name: "Latest Post-SPAC Merger Share Registration S-1 Link",
    key: "LatestPostSPACMergerShareRegistrationS1Link",
    type: "string",
    pro: true,
  },
  {
    name: "Post-SPAC Merger Share Registration Effective Date",
    key: "PostSPACMergerShareRegistrationEffectiveDate",
    type: "string",
    pro: true,
  },
  {
    name: "Liquidation Date",
    key: "LiquidationDate",
    type: "string",
    pro: true,
  },
  {
    name: "Liquidation Redemption Price",
    key: "LiquidationRedemptionPrice",
    type: "string",
    pro: true,
  },
  {
    name: "Liquidation Announcement Link",
    key: "LiquidationAnnouncementLink",
    type: "string",
    pro: true,
  },
  {
    name: "Liquidation Trust Value",
    key: "LiquidationTrustValue",
    type: "string",
    pro: true,
  },
];
export const TrustRedemptions = [
  {
    name: "Est. Trust Value",
    key: "EstTrustValue",
    type: "string",
    pro: false,
  },
  {
    name: "Trust per Share",
    key: "TrustperShare",
    type: "string",
    pro: false,
  },
  {
    name: "Trust Per Share Date",
    key: "TrustPerShareDate",
    type: "string",
    pro: false,
  },
  {
    name: "Est. Shares Remaining Pre-Close (M)",
    key: "EstSharesRemainingPreCloseM",
    type: "string",
    pro: false,
  },
  {
    name: "Est. Shares Remaining Post-Close (M)",
    key: "EstSharesRemainingPostCloseM",
    type: "string",
    pro: false,
  },
  {
    name: "Trust P.S. at IPO",
    key: "TrustPSatIPO",
    type: "string",
    pro: true,
  },
  {
    name: "Trust per Share Source",
    key: "TrustperShareSource",
    type: "string",
    pro: true,
  },
  {
    name: "Trading Premium/Discount",
    key: "TradingPremiumDiscount",
    type: "string",
    pro: true,
  },
  {
    name: "SPAC Shares Redeemed at Merger Vote (%)",
    key: "SPACSharesRedeemedatMergerVote",
    type: "string",
    pro: true,
  },
  {
    name: "SPAC Shares Redeemed Lifetime (%)",
    key: "SPACSharesRedeemedLifetime",
    type: "string",
    pro: true,
  },
];

export const AnnouncedSPACMergersScreener = [
  {
    name: "Deal Name",
    key: "DealName",
    type: "string",
    pro: false,
  },
  {
    name: "Acquirer Company Name",
    key: "AcquirerCompanyName",
    type: "string",
    pro: false,
  },
  {
    name: "Acquirer Symbol",
    key: "AcquirerSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Acquirer Listing Status",
    key: "AcquirerListingStatus",
    type: "string",
    pro: false,
  },
  {
    name: "Target Company Name",
    key: "TargetCompanyName",
    type: "string",
    pro: false,
  },
  {
    name: "Target Symbol",
    key: "TargetSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Merger Announced Date",
    key: "MergerAnnouncedDate",
    type: "string",
    pro: false,
  },
  {
    name: "Deal Valuation",
    key: "DealValuation",
    type: "string",
    pro: false,
  },
  {
    name: "Price per Share",
    key: "PriceperShare",
    type: "string",
    pro: false,
  },
  {
    name: "Current Premium",
    key: "CurrentPremium",
    type: "string",
    pro: false,
  },
  {
    name: "PIPE Equity Proceeds",
    key: "PIPEEquityProceeds",
    type: "string",
    pro: false,
  },
  {
    name: "Announced PIPE Investors",
    key: "AnnouncedPIPEInvestors",
    type: "string",
    pro: false,
  },
  {
    name: "Target Merger Vote Date",
    key: "TargetMergerVoteDate",
    type: "string",
    pro: false,
  },
  {
    name: "Closing Date",
    key: "ClosingDate",
    type: "string",
    pro: false,
  },
  {
    name: "Merger Type",
    key: "MergerType",
    type: "string",
    pro: true,
  },
  {
    name: "Target Listing Status",
    key: "TargetListingStatus",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Announcement Link",
    key: "MergerAnnouncementLink",
    type: "string",
    pro: true,
  },
  {
    name: "Investor Presentation Link",
    key: "InvestorPresentationLink",
    type: "string",
    pro: true,
  },
  {
    name: "BCA Link",
    key: "BCALink",
    type: "string",
    pro: true,
  },
  {
    name: "Deal Valuation Summary",
    key: "DealValuationSummary",
    type: "string",
    pro: true,
  },
  {
    name: "Premium at Deal Announcement",
    key: "PremiumatDealAnnouncement",
    type: "string",
    pro: true,
  },
  {
    name: "Funding Summary",
    key: "FundingSummary",
    type: "string",
    pro: true,
  },
  {
    name: "S-4 Link",
    key: "S4Link",
    type: "string",
    pro: true,
  },
  {
    name: "Expected Closing Date",
    key: "ExpectedClosingDate",
    type: "string",
    pro: true,
  },
  {
    name: "Target Prelim Merger Vote Proxy Link",
    key: "TargetPrelimMergerVoteProxyLink",
    type: "string",
    pro: true,
  },
  {
    name: "Target Definitive Merger Vote Link",
    key: "TargetDefinitiveMergerVoteLink",
    type: "string",
    pro: true,
  },
  {
    name: "Outside Date",
    key: "OutsideDate",
    type: "string",
    pro: true,
  },
  {
    name: "Closing Announcement Link",
    key: "ClosingAnnouncementLink",
    type: "string",
    pro: true,
  },
  {
    name: "Financial Historicals Slide from Investor Deck",
    key: "FinancialHistoricalsSlidefromInvestorDeck",
    type: "string",
    pro: true,
  },
  {
    name: "Latest Transaction Overview Slide",
    key: "LatestTransactionOverviewSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Comparable Landscape Slide",
    key: "ComparableLandscapeSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Operational Benchmarking Slide",
    key: "OperationalBenchmarkingSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Competitive Valuation Benchmarking Slide ",
    key: "CompetitiveValuationBenchmarkingSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Financial Projections Slide from Investor Deck",
    key: "FinancialProjectionsSlidefromInvestorDeck",
    type: "string",
    pro: true,
  },
  {
    name: "Post-Merger SEC Filings Link",
    key: "PostMergerSECFilingsLink",
    type: "string",
    pro: true,
  },
  {
    name: "Terminated Date",
    key: "TerminatedDate",
    type: "string",
    pro: true,
  },
  {
    name: "Terminated Source Link",
    key: "TerminatedSourceLink",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Rumor Date",
    key: "MergerRumorDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Rumor Publication",
    key: "MergerRumorPublication",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Rumor Source",
    key: "MergerRumorSource",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Talks Failed Date",
    key: "MergerTalksFailedDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Talks Failed Publication",
    key: "MergerTalksFailedPublication",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Talks Failed Source",
    key: "MergerTalksFailedSource",
    type: "string",
    pro: true,
  },
];

export const DealProfile = [
  {
    name: "Deal Name",
    key: "DealName",
    type: "string",
    pro: false,
  },
  {
    name: "Acquirer Company Name",
    key: "AcquirerCompanyName",
    type: "string",
    pro: false,
  },
  {
    name: "Acquirer Symbol",
    key: "AcquirerSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Acquirer Listing Status",
    key: "AcquirerListingStatus",
    type: "string",
    pro: false,
  },
  {
    name: "Target Company Name",
    key: "TargetCompanyName",
    type: "string",
    pro: false,
  },
  {
    name: "Target Symbol",
    key: "TargetSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Merger Announced Date",
    key: "MergerAnnouncedDate",
    type: "string",
    pro: false,
  },
  {
    name: "Deal Valuation",
    key: "DealValuation",
    type: "string",
    pro: false,
  },
  {
    name: "Price per Share",
    key: "PriceperShare",
    type: "string",
    pro: false,
  },
  {
    name: "Current Premium",
    key: "CurrentPremium",
    type: "string",
    pro: false,
  },
  {
    name: "PIPE Equity Proceeds",
    key: "PIPEEquityProceeds",
    type: "string",
    pro: false,
  },
  {
    name: "Announced PIPE Investors",
    key: "AnnouncedPIPEInvestors",
    type: "string",
    pro: false,
  },
  {
    name: "Target Merger Vote Date",
    key: "TargetMergerVoteDate",
    type: "string",
    pro: false,
  },
  {
    name: "Closing Date",
    key: "ClosingDate",
    type: "string",
    pro: false,
  },
  {
    name: "Merger Type",
    key: "MergerType",
    type: "string",
    pro: true,
  },
  {
    name: "Target Listing Status",
    key: "TargetListingStatus",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Announcement Link",
    key: "MergerAnnouncementLink",
    type: "string",
    pro: true,
  },
  {
    name: "Investor Presentation Link",
    key: "InvestorPresentationLink",
    type: "string",
    pro: true,
  },
  {
    name: "BCA Link",
    key: "BCALink",
    type: "string",
    pro: true,
  },
  {
    name: "Deal Valuation Summary",
    key: "DealValuationSummary",
    type: "string",
    pro: true,
  },
  {
    name: "Premium at Deal Announcement",
    key: "PremiumatDealAnnouncement",
    type: "string",
    pro: true,
  },
  {
    name: "Funding Summary",
    key: "FundingSummary",
    type: "string",
    pro: true,
  },
  {
    name: "S-4 Link",
    key: "S4Link",
    type: "string",
    pro: true,
  },
  {
    name: "Expected Closing Date",
    key: "ExpectedClosingDate",
    type: "string",
    pro: true,
  },
  {
    name: "Target Prelim Merger Vote Proxy Link",
    key: "TargetPrelimMergerVoteProxyLink",
    type: "string",
    pro: true,
  },
  {
    name: "Target Definitive Merger Vote Link",
    key: "TargetDefinitiveMergerVoteLink",
    type: "string",
    pro: true,
  },
  {
    name: "Outside Date",
    key: "OutsideDate",
    type: "string",
    pro: true,
  },
  {
    name: "Closing Announcement Link",
    key: "ClosingAnnouncementLink",
    type: "string",
    pro: true,
  },
  {
    name: "Post-Merger SEC Filings Link",
    key: "PostMergerSECFilingsLink",
    type: "string",
    pro: true,
  },
];
export const SPACTargetProfile = [
  {
    name: "Financial Historicals Slide from Investor Deck",
    key: "FinancialHistoricalsSlidefromInvestorDeck",
    type: "string",
    pro: true,
  },
  {
    name: "Latest Transaction Overview Slide",
    key: "LatestTransactionOverviewSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Comparable Landscape Slide",
    key: "ComparableLandscapeSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Operational Benchmarking Slide",
    key: "OperationalBenchmarkingSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Competitive Valuation Benchmarking Slide ",
    key: "CompetitiveValuationBenchmarkingSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Financial Projections Slide from Investor Deck",
    key: "FinancialProjectionsSlidefromInvestorDeck",
    type: "string",
    pro: true,
  },
];
export const RumorsTerminations = [
  {
    name: "Terminated Date",
    key: "TerminatedDate",
    type: "string",
    pro: true,
  },
  {
    name: "Terminated Source Link",
    key: "TerminatedSourceLink",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Rumor Date",
    key: "MergerRumorDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Rumor Publication",
    key: "MergerRumorPublication",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Rumor Source",
    key: "MergerRumorSource",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Talks Failed Date",
    key: "MergerTalksFailedDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Talks Failed Publication",
    key: "MergerTalksFailedPublication",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Talks Failed Source",
    key: "MergerTalksFailedSource",
    type: "string",
    pro: true,
  },
];

export const DeSPACScreener = [
  {
    name: "Company",
    key: "company",
    type: "string",
    pro: false,
  },
  {
    name: "Symbol",
    key: "symbol",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Method",
    key: "listing_method",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Status",
    key: "listing_status",
    type: "string",
    pro: false,
  },
  {
    name: "Exchange",
    key: "daily",
    type: "string",
    pro: false,
  },
  {
    name: "Market Cap",
    key: "marketCap",
    type: "string",
    pro: false,
  },
  {
    name: "Region",
    key: "Region",
    type: "string",
    pro: true,
  },
  {
    name: "Sector",
    key: "Sector",
    type: "string",
    pro: true,
  },
  {
    name: "Industry",
    key: "Industry",
    type: "string",
    pro: true,
  },
  {
    name: "HQ City, Country",
    key: "HQCityCountry",
    type: "string",
    pro: true,
  },
  {
    name: "Employees",
    key: "Employees",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Status",
    key: "IPOStatus",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Type",
    key: "IPOType",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Price",
    key: "IPOPrice",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Date",
    key: "IPODate",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Proceeds",
    key: "IPOProceeds",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Underwriters",
    key: "IPOUnderwriters",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Date",
    key: "ExpectedIPODate",
    type: "string",
    pro: false,
  },
  {
    name: "ExpectedIPOShares",
    key: "ExpectedIPOShares",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Price Range",
    key: "ExpectedIPOPriceRange",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Valuation",
    key: "ExpectedIPOValuation",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Market Cap",
    key: "IPOMarketCap",
    type: "string",
    pro: true,
  },
  {
    name: "IPO S-1 Registration Link",
    key: "IPOS1RegistrationLink",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Filed Date",
    key: "IPOFiledDate",
    type: "string",
    pro: true,
  },
  {
    name: "Registration Domicile",
    key: "RegistrationDomicile",
    type: "string",
    pro: true,
  },
  {
    name: "S-1 Withdrawal Date",
    key: "S1WithdrawalDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Date",
    key: "IPORumorDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Publication",
    key: "IPORumorPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Source",
    key: "IPORumorSource",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Date",
    key: "IPOStallDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Publication",
    key: "IPOStallPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Source",
    key: "IPOStallSource",
    type: "string",
    pro: true,
  },
  {
    name: "Latest Price",
    key: "LatestPrice",
    type: "string",
    pro: false,
  },
  {
    name: "1-day Price Chg %",
    key: "1dayPriceChg",
    type: "string",
    pro: false,
  },
  {
    name: "Outstanding Shares",
    key: "OutstandingShares",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week High",
    key: "52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week Low",
    key: "52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week High Percent Change",
    key: "52WeekHighPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week Low Percent Change",
    key: "52WeekLowPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Volume",
    key: "Volume",
    type: "string",
    pro: false,
  },
  {
    name: "Average 30 Day Volume",
    key: "Average30DayVolume",
    type: "string",
    pro: false,
  },
  {
    name: "YTD Percent Change",
    key: "YTDPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Optionable",
    key: "Optionable",
    type: "string",
    pro: false,
  },
  {
    name: "1-week Percent Change ",
    key: "1weekPercentChange ",
    type: "string",
    pro: true,
  },
  {
    name: "30-day Change Percent",
    key: "30dayChangePercent",
    type: "string",
    pro: true,
  },
  {
    name: "1-month Percent Change",
    key: "1monthPercentChange",
    type: "string",
    pro: true,
  },
  {
    name: "3-month Percent Change",
    key: "3monthPercentChange",
    type: "string",
    pro: true,
  },
  {
    name: "1-year Percent Change ",
    key: "1yearPercentChange ",
    type: "string",
    pro: true,
  },
];

export const Extension = [
  {
    name: "Ext. Vote Date",
    key: "ExtVoteDate",
    type: "string",
    pro: false,
  },
  {
    name: "Ext. Red. Deadline",
    key: "ExtRedDeadline",
    type: "string",
    pro: false,
  },
  {
    name: "Ext. Ex-Red. Date",
    key: "ExtExRedDeadline",
    type: "string",
    pro: false,
  },
  {
    name: "Ext. Vote Proxy",
    key: "ExtVoteProxy",
    type: "string",
    pro: false,
  },
  {
    name: "Trust per Share at Proxy",
    key: "ExtTrustProxy",
    type: "string",
    pro: false,
  },
  {
    name: "Ext. Vote Proposal",
    key: "ExtVoteProposal",
    type: "string",
    pro: false,
  },
  {
    name: "Ext. Vote Notes",
    key: "ExtVoteNote",
    type: "string",
    pro: false,
  },
];

export const Mergers = [
  {
    name: "Merger Vote Date",
    key: "MergerVoteDate",
    type: "string",
    pro: false,
  },
  {
    name: "Merger. Red. Deadline",
    key: "MergerRedDeadline",
    type: "string",
    pro: false,
  },
  {
    name: "Merger Ex-Red. Date",
    key: "MergerExRedDeadline",
    type: "string",
    pro: false,
  },
  {
    name: "Merger Vote Proxy",
    key: "MergerVoteProxy",
    type: "string",
    pro: false,
  },
  {
    name: "Trust per Share at Proxy",
    key: "MergerTrustProxy",
    type: "string",
    pro: false,
  },
  {
    name: "Merger Vote Notes",
    key: "MergerVoteNote",
    type: "string",
    pro: false,
  },
  {
    name: "Expected Closing Date",
    key: "ExpClosingDate",
    type: "string",
    pro: false,
  },
  {
    name: "Expected Ticker Change Date",
    key: "ExpTicChangeDate",
    type: "string",
    pro: false,
  },
];

export const IPOAndSplitDates = [
  {
    name: "Expected IPO Date",
    key: "ExpIPODate",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Date",
    key: "IPODate",
    type: "string",
    pro: false,
  },
  {
    name: "Estimated Split Date",
    key: "EstSplitDate",
    type: "string",
    pro: false,
  },
  {
    name: "Confirmed Split Date",
    key: "ConfSplitDate",
    type: "string",
    pro: false,
  },
];

export const IPOPricedScreeners = [
  {
    name: "Company",
    key: "company",
    type: "string",
    pro: false,
  },
  {
    name: "Symbol",
    key: "symbol",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Method",
    key: "listing_method",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Status",
    key: "listing_status",
    type: "string",
    pro: false,
  },
  {
    name: "Exchange",
    key: "daily",
    type: "string",
    pro: false,
  },
  {
    name: "Market Cap",
    key: "marketCap",
    type: "string",
    pro: false,
  },
  {
    name: "Region",
    key: "Region",
    type: "string",
    pro: true,
  },
  {
    name: "Sector",
    key: "Sector",
    type: "string",
    pro: true,
  },
  {
    name: "Industry",
    key: "Industry",
    type: "string",
    pro: true,
  },
  {
    name: "HQ City, Country",
    key: "HQCityCountry",
    type: "string",
    pro: true,
  },
  {
    name: "Employees",
    key: "Employees",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Status",
    key: "IPOStatus",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Type",
    key: "IPOType",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Price",
    key: "IPOPrice",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Date",
    key: "IPODate",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Proceeds",
    key: "IPOProceeds",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Underwriters",
    key: "IPOUnderwriters",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Date",
    key: "ExpectedIPODate",
    type: "string",
    pro: false,
  },
  {
    name: "ExpectedIPOShares",
    key: "ExpectedIPOShares",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Price Range",
    key: "ExpectedIPOPriceRange",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Valuation",
    key: "ExpectedIPOValuation",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Market Cap",
    key: "IPOMarketCap",
    type: "string",
    pro: true,
  },
  {
    name: "IPO S-1 Registration Link",
    key: "IPOS1RegistrationLink",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Filed Date",
    key: "IPOFiledDate",
    type: "string",
    pro: true,
  },
  {
    name: "Registration Domicile",
    key: "RegistrationDomicile",
    type: "string",
    pro: true,
  },
  {
    name: "S-1 Withdrawal Date",
    key: "S1WithdrawalDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Date",
    key: "IPORumorDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Publication",
    key: "IPORumorPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Source",
    key: "IPORumorSource",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Date",
    key: "IPOStallDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Publication",
    key: "IPOStallPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Source",
    key: "IPOStallSource",
    type: "string",
    pro: true,
  },
  {
    name: "Latest Price",
    key: "LatestPrice",
    type: "string",
    pro: false,
  },
  {
    name: "1-day Price Chg %",
    key: "1dayPriceChg",
    type: "string",
    pro: false,
  },
  {
    name: "Outstanding Shares",
    key: "OutstandingShares",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week High",
    key: "52WeekHigh",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week Low",
    key: "52WeekLow",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week High Percent Change",
    key: "52WeekHighPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "52-Week Low Percent Change",
    key: "52WeekLowPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Volume",
    key: "Volume",
    type: "string",
    pro: false,
  },
  {
    name: "Average 30 Day Volume",
    key: "Average30DayVolume",
    type: "string",
    pro: false,
  },
  {
    name: "YTD Percent Change",
    key: "YTDPercentChange",
    type: "string",
    pro: false,
  },
  {
    name: "Optionable",
    key: "Optionable",
    type: "string",
    pro: false,
  },
  {
    name: "1-week Percent Change ",
    key: "1weekPercentChange ",
    type: "string",
    pro: true,
  },
  {
    name: "30-day Change Percent",
    key: "30dayChangePercent",
    type: "string",
    pro: true,
  },
  {
    name: "1-month Percent Change",
    key: "1monthPercentChange",
    type: "string",
    pro: true,
  },
  {
    name: "3-month Percent Change",
    key: "3monthPercentChange",
    type: "string",
    pro: true,
  },
  {
    name: "1-year Percent Change ",
    key: "1yearPercentChange ",
    type: "string",
    pro: true,
  },
];

export const IPOUpcommingScreeners = [
  {
    name: "Company",
    key: "company",
    type: "string",
    pro: false,
  },
  {
    name: "Symbol",
    key: "symbol",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Method",
    key: "listing_method",
    type: "string",
    pro: false,
  },
  {
    name: "Listing Status",
    key: "listing_status",
    type: "string",
    pro: false,
  },
  {
    name: "Exchange",
    key: "daily",
    type: "string",
    pro: false,
  },
  {
    name: "Market Cap",
    key: "marketCap",
    type: "string",
    pro: false,
  },
  {
    name: "Region",
    key: "Region",
    type: "string",
    pro: true,
  },
  {
    name: "Sector",
    key: "Sector",
    type: "string",
    pro: true,
  },
  {
    name: "Industry",
    key: "Industry",
    type: "string",
    pro: true,
  },
  {
    name: "HQ City, Country",
    key: "HQCityCountry",
    type: "string",
    pro: true,
  },
  {
    name: "Employees",
    key: "Employees",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Status",
    key: "IPOStatus",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Type",
    key: "IPOType",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Price",
    key: "IPOPrice",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Date",
    key: "IPODate",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Proceeds",
    key: "IPOProceeds",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Underwriters",
    key: "IPOUnderwriters",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Date",
    key: "ExpectedIPODate",
    type: "string",
    pro: false,
  },
  {
    name: "ExpectedIPOShares",
    key: "ExpectedIPOShares",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Price Range",
    key: "ExpectedIPOPriceRange",
    type: "string",
    pro: false,
  },
  {
    name: "Expected IPO Valuation",
    key: "ExpectedIPOValuation",
    type: "string",
    pro: false,
  },
  {
    name: "IPO Market Cap",
    key: "IPOMarketCap",
    type: "string",
    pro: true,
  },
  {
    name: "IPO S-1 Registration Link",
    key: "IPOS1RegistrationLink",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Filed Date",
    key: "IPOFiledDate",
    type: "string",
    pro: true,
  },
  {
    name: "Registration Domicile",
    key: "RegistrationDomicile",
    type: "string",
    pro: true,
  },
  {
    name: "S-1 Withdrawal Date",
    key: "S1WithdrawalDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Date",
    key: "IPORumorDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Publication",
    key: "IPORumorPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Rumor Source",
    key: "IPORumorSource",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Date",
    key: "IPOStallDate",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Publication",
    key: "IPOStallPublication",
    type: "string",
    pro: true,
  },
  {
    name: "IPO Stall Source",
    key: "IPOStallSource",
    type: "string",
    pro: true,
  },
];

export const ClosedMergersScreener = [
  {
    name: "Deal Name",
    key: "DealName",
    type: "string",
    pro: false,
  },
  {
    name: "Acquirer Company Name",
    key: "AcquirerCompanyName",
    type: "string",
    pro: false,
  },
  {
    name: "Acquirer Symbol",
    key: "AcquirerSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Acquirer Listing Status",
    key: "AcquirerListingStatus",
    type: "string",
    pro: false,
  },
  {
    name: "Target Company Name",
    key: "TargetCompanyName",
    type: "string",
    pro: false,
  },
  {
    name: "Target Symbol",
    key: "TargetSymbol",
    type: "string",
    pro: false,
  },
  {
    name: "Merger Announced Date",
    key: "MergerAnnouncedDate",
    type: "string",
    pro: false,
  },
  {
    name: "Deal Valuation",
    key: "DealValuation",
    type: "string",
    pro: false,
  },
  {
    name: "Price per Share",
    key: "PriceperShare",
    type: "string",
    pro: false,
  },
  {
    name: "Current Premium",
    key: "CurrentPremium",
    type: "string",
    pro: false,
  },
  {
    name: "PIPE Equity Proceeds",
    key: "PIPEEquityProceeds",
    type: "string",
    pro: false,
  },
  {
    name: "Announced PIPE Investors",
    key: "AnnouncedPIPEInvestors",
    type: "string",
    pro: false,
  },
  {
    name: "Target Merger Vote Date",
    key: "TargetMergerVoteDate",
    type: "string",
    pro: false,
  },
  {
    name: "Closing Date",
    key: "ClosingDate",
    type: "string",
    pro: false,
  },
  {
    name: "Merger Type",
    key: "MergerType",
    type: "string",
    pro: true,
  },
  {
    name: "Target Listing Status",
    key: "TargetListingStatus",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Announcement Link",
    key: "MergerAnnouncementLink",
    type: "string",
    pro: true,
  },
  {
    name: "Investor Presentation Link",
    key: "InvestorPresentationLink",
    type: "string",
    pro: true,
  },
  {
    name: "BCA Link",
    key: "BCALink",
    type: "string",
    pro: true,
  },
  {
    name: "Deal Valuation Summary",
    key: "DealValuationSummary",
    type: "string",
    pro: true,
  },
  {
    name: "Premium at Deal Announcement",
    key: "PremiumatDealAnnouncement",
    type: "string",
    pro: true,
  },
  {
    name: "Funding Summary",
    key: "FundingSummary",
    type: "string",
    pro: true,
  },
  {
    name: "S-4 Link",
    key: "S4Link",
    type: "string",
    pro: true,
  },
  {
    name: "Expected Closing Date",
    key: "ExpectedClosingDate",
    type: "string",
    pro: true,
  },
  {
    name: "Target Prelim Merger Vote Proxy Link",
    key: "TargetPrelimMergerVoteProxyLink",
    type: "string",
    pro: true,
  },
  {
    name: "Target Definitive Merger Vote Link",
    key: "TargetDefinitiveMergerVoteLink",
    type: "string",
    pro: true,
  },
  {
    name: "Outside Date",
    key: "OutsideDate",
    type: "string",
    pro: true,
  },
  {
    name: "Closing Announcement Link",
    key: "ClosingAnnouncementLink",
    type: "string",
    pro: true,
  },
  {
    name: "Financial Historicals Slide from Investor Deck",
    key: "FinancialHistoricalsSlidefromInvestorDeck",
    type: "string",
    pro: true,
  },
  {
    name: "Latest Transaction Overview Slide",
    key: "LatestTransactionOverviewSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Comparable Landscape Slide",
    key: "ComparableLandscapeSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Operational Benchmarking Slide",
    key: "OperationalBenchmarkingSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Competitive Valuation Benchmarking Slide ",
    key: "CompetitiveValuationBenchmarkingSlide",
    type: "string",
    pro: true,
  },
  {
    name: "Financial Projections Slide from Investor Deck",
    key: "FinancialProjectionsSlidefromInvestorDeck",
    type: "string",
    pro: true,
  },
  {
    name: "Post-Merger SEC Filings Link",
    key: "PostMergerSECFilingsLink",
    type: "string",
    pro: true,
  },
  {
    name: "Terminated Date",
    key: "TerminatedDate",
    type: "string",
    pro: true,
  },
  {
    name: "Terminated Source Link",
    key: "TerminatedSourceLink",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Rumor Date",
    key: "MergerRumorDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Rumor Publication",
    key: "MergerRumorPublication",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Rumor Source",
    key: "MergerRumorSource",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Talks Failed Date",
    key: "MergerTalksFailedDate",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Talks Failed Publication",
    key: "MergerTalksFailedPublication",
    type: "string",
    pro: true,
  },
  {
    name: "Merger Talks Failed Source",
    key: "MergerTalksFailedSource",
    type: "string",
    pro: true,
  },
];

export const marketingConstants = {
  ListingTracker: "Listing Tracker",
  IPOPORTAL: "IPO PORTAL",
  MERGERPORTAL: "MERGER PORTAL",
  SPACPORTAL: "SPAC PORTAL",
  details:
    "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia.",
  VIEWDashboard: "VIEW DASHBOARD",
  VIEWIPOS: "VIEW IPOS",
  VIEWMERGERS: "VIEW MERGERS",
  THEPOWEROFPRO: "THE POWER OF PRO",
  THEPOWEROFPRODETAILS:
    "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, for just $60 per month, or $500 annually.",
  BROUGHTTOYOUBYTHEcreatorsOFSPACtrackASMENTIONEDIN:
    "BROUGHT TO YOU BY THE CREATORS OF SPAC TRACK, AS MENTIONED IN: ",

  GETFREEUPDATESTOYOURINBOX: "GET FREE UPDATES TO YOUR INBOX",
  GETFREEUPDATESTOYOURINBOXDETAILS:
    "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut ofegd.",
};

export const memberstack_config = {
  publicKey: `${process.env.NEXT_PUBLIC_MEMBERSTACK_KEY}`,
  appId: undefined,
  sessionDurationDays: undefined,
  useCookies: undefined,
  domain: undefined,
}
