name: React.JS CI/CD (DEV)

on:
  push:
    branches: [ dev ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm test

    - name: Prepare Deployment
      run: npm run prepare-deployment
      
    - name: Set version label
      id: prep
      run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/})-${GITHUB_SHA::8}"      

    - name: Deploy to AWS Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: listingtrack-ui
        environment_name: staging-ui
        version_label: git-action ${{ steps.prep.outputs.version }}
        region: us-east-1
        deployment_package: build.zip
